name: qtwebbrowser # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Qt based web browser with virtual keyboard # 79 char long summary
description: |
  This is QT base Web Browser targeted to embedded devices. It bas built-in
  virtual keyboard and a lot of features.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/qtwebbrowser
    daemon: simple
    restart-condition: always

  qtwebbrowser:
    command-chain:
      - bin/wayland-launch
    command: bin/qtwebbrowser

plugs:
  network:
  opengl:
  wayland:


layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/xdg:
    bind: $SNAP/etc/xdg
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri


environment:
  # Qt Platform to Wayland
  QT_QPA_PLATFORM: wayland
  QTCHOOSER_NO_GLOBAL_DIR: 1
  QT_SELECT: snappy-qt5

parts:
  qtwayland:
    plugin: nil
    stage-packages:
      - qtwayland5

  qtwebbrowser:
    source: .
    plugin: qmake
    qt-version: qt5
    project-files: [qtwebbrowser.pro]
    after: [desktop-qt5]
    stage-packages:
    # QT Quick Modules
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick-extras
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick-virtualkeyboard
      - qml-module-qt-labs-settings
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-controls2
      - qml-module-qtwebengine
      - qml-module-qtwebkit
      - qml-module-qtwebview
      - qtvirtualkeyboard-plugin

  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
      - qtdeclarative5-dev
      - qtwebengine5-dev
      - libqt5webkit5-dev
      - libqt5webview5
      - qtbase5-private-dev
      - libappindicator-dev
    make-parameters:
     - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try:
        - appmenu-qt5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  qtchooser-config:
    plugin: dump
    source: qtconfig
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf


  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build: $SNAPCRAFT_PART_BUILD/build-with-plugs.sh network opengl wayland
    stage-packages:
      - inotify-tools

  inotify-tools:
    plugin: nil
    stage-packages: [inotify-tools]
    prime:
     - usr/bin/inotifywait
     - usr/lib