name: qtwebbrowser # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Qt based web browser with virtual keyboard # 79 char long summary
description: |
  This is QT base Web Browser targeted to embedded devices. It bas built-in
  virtual keyboard and a lot of features.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/usr/local/bin/qtwebbrowser --no-sandbox http://www.google.com/
    plugs:
      - opengl         # For Mir
      - wayland        # For Mir
      - network
      - network-bind   # For Mir (to serve X11)
      - browser-support


architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf


environment:
  # Qt Platform to Wayland
  QT_QPA_PLATFORM: xcb
  QTCHOOSER_NO_GLOBAL_DIR: 1
  QT_SELECT: snappy-qt5

parts:
  qtwayland:
    plugin: nil
    stage-packages:
      - qtwayland5
  
  qtwebbrowser:
    source: .
    plugin: qmake
    qmake-project-file: qtwebbrowser.pro
    after: [desktop-qt5]
    stage-packages:
    # QT Quick Modules
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick-extras
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick-virtualkeyboard
      - qml-module-qt-labs-settings
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-controls2
      - qml-module-qtwebengine
      - qml-module-qtwebkit
      - qml-module-qtwebview
      - qtvirtualkeyboard-plugin
    stage-snaps: [mir-kiosk-x11]

  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
      - qtdeclarative5-dev
      - qtwebengine5-dev
      - libqt5webkit5-dev
      - libqt5webview5
      - qtbase5-private-dev
      - libappindicator-dev
    make-parameters:
     - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try:
        - appmenu-qt5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  qtchooser-config:
    plugin: dump
    source: qtconfig
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf



# Needed by Mir and/or Xwayland
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
